# Generated by Django 5.1.3 on 2024-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='C:/Users/hp/Pictures/pp.pp.jpg'),
        ),
    ]
